#! /usr/bin/env bash



aws ssm send-command \
    --document-name Reboot-Instance \
    --instance-ids i-0e5daa43d7c49c964 \
    --comment "Reboot instance" \
    --region "us-east-1"

    # --targets "Key=instanceids,Values=i-0e5daa43d7c49c964" \