tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      clear
  - name: utils
    init: |
      sudo apt-get install -y dnsutils
      pip
      clear
  - name: python
    init: |
      sudo apt update
      sudo apt install -y python3
      sudo apt install -y python3-venv
      sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
      python3 -m venv venv
      . venv/bin/activate
      pip install -r config/requirements.txt
      export FLASK_APP=__init__.py
      export FLASK_DEBUG=1
      cd flaskapp
      clear

