tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      clear
  - name: utils
    init: |
      sudo apt-get install -y dnsutils
      pip
      clear
  - name: python-venv
    init: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r config/requirements.txt
      clear
      

