version: 0.0
os: linux
files:
  - source: SourceArtifact
    destination: /var/www
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root